package br.com.cesarsicas.androidmovieflix.domain.model

data class TitleDetailsModel(
    val id: Int,
    val title: String,
    val originalTitle: String,
    val plotOverview: String,
    val type: String,
    val runtimeMinutes: Int?,
    val year: Int?,
    val endYear: Int?,
    val releaseDate: String?,
    val imdbId: String?,
    val tmdbId: Int?,
    val tmdbType: String?,
    val genres: List<Int>?,
    val genreNames: List<String>?,
    val similarTitles: List<Int>?,
    val networks: List<Int>?,
    val networkNames: List<String>?,
    val userRating: Double?,
    val criticScore: Int?,
    val relevancePercentile: Double?,
    val usRating: String?,
    val poster: String?,
    val backdrop: String?,
    val originalLanguage: String?,
    val trailer: String?,
    val trailerThumbnail: String?,
    val cast: List<CastMemberModel>?,
)
